### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by busticated** [busticated/01110000#1]
so i don't forget :)

- [ ] add view transition animations
- [ ] fix libraries paging controls (currently, they bounce around as you page)
- [ ] fix responsiveness for or ditch tables in SDK detail view
- [ ] less annoying status / busy indicator UI
- [ ] add a manifest.json (needs art)
- [ ] offline / no network status message
- [ ] refine server-side caching strategy (currently disabled in favor of service worker cache for simplicity)
- [ ] nit: rename `lastPageFetched` -> `pageToFetch` in [client/app.js](https://github.com/busticated/01110000/blob/v1.0.0/src/client/components/app.js#L33)
- [ ] figure out better secret management (currently too manual imho)
- [ ] clean up sass lib usage
- [ ] add formal `Library` model
- [ ] tune karma bits (watch mode is a bit squirrelly, source maps are wonky)
